#!/bin/sh

if [ -d build -a -e build/Makefile ]; then
    cd build && make rebuild_cache || exit 1
else
    if [ ! -d build ]; then
      mkdir build || exit 1
    fi
    cd build && cmake -Wdev -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr .. || exit 1
fi

make all || exit 1
cd ..

#LD_LIBRARY_PATH=build exec gdb -ex "handle SIGPIPE nostop noprint pass" -ex "run" --args ./build/spopd $@
LD_LIBRARY_PATH=build exec ./build/spopd $@
