/*
 * Generated by gdbus-codegen 2.35.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __MPRIS2_PLAYER_GENERATED_H__
#define __MPRIS2_PLAYER_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.mpris.MediaPlayer2.Player */

#define MPRIS2_TYPE_PLAYER (mpris2_player_get_type ())
#define MPRIS2_PLAYER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS2_TYPE_PLAYER, Mpris2Player))
#define MPRIS2_IS_PLAYER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS2_TYPE_PLAYER))
#define MPRIS2_PLAYER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MPRIS2_TYPE_PLAYER, Mpris2PlayerIface))

struct _Mpris2Player;
typedef struct _Mpris2Player Mpris2Player;
typedef struct _Mpris2PlayerIface Mpris2PlayerIface;

struct _Mpris2PlayerIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_next) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_open_uri) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_Uri);

  gboolean (*handle_pause) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play_pause) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_previous) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_seek) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation,
    gint64 arg_Offset);

  gboolean (*handle_set_position) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_TrackId,
    gint64 arg_Position);

  gboolean (*handle_stop) (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_can_control) (Mpris2Player *object);

  gboolean  (*get_can_go_next) (Mpris2Player *object);

  gboolean  (*get_can_go_previous) (Mpris2Player *object);

  gboolean  (*get_can_pause) (Mpris2Player *object);

  gboolean  (*get_can_play) (Mpris2Player *object);

  gboolean  (*get_can_seek) (Mpris2Player *object);

  const gchar * (*get_loop_status) (Mpris2Player *object);

  gdouble  (*get_maximum_rate) (Mpris2Player *object);

  GVariant * (*get_metadata) (Mpris2Player *object);

  gdouble  (*get_minimum_rate) (Mpris2Player *object);

  const gchar * (*get_playback_status) (Mpris2Player *object);

  gint64  (*get_position) (Mpris2Player *object);

  gdouble  (*get_rate) (Mpris2Player *object);

  gboolean  (*get_shuffle) (Mpris2Player *object);

  gdouble  (*get_volume) (Mpris2Player *object);

  void (*seeked) (
    Mpris2Player *object,
    gint64 arg_Position);

};

GType mpris2_player_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *mpris2_player_interface_info (void);
guint mpris2_player_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void mpris2_player_complete_next (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_previous (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_pause (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_play_pause (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_stop (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_play (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_seek (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_set_position (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);

void mpris2_player_complete_open_uri (
    Mpris2Player *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void mpris2_player_emit_seeked (
    Mpris2Player *object,
    gint64 arg_Position);



/* D-Bus method calls: */
void mpris2_player_call_next (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_next_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_next_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_previous (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_previous_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_previous_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_pause (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_pause_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_pause_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_play_pause (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_play_pause_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_play_pause_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_stop (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_stop_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_stop_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_play (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_play_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_play_sync (
    Mpris2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_seek (
    Mpris2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_seek_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_seek_sync (
    Mpris2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_set_position (
    Mpris2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_set_position_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_set_position_sync (
    Mpris2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GError **error);

void mpris2_player_call_open_uri (
    Mpris2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean mpris2_player_call_open_uri_finish (
    Mpris2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean mpris2_player_call_open_uri_sync (
    Mpris2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *mpris2_player_get_playback_status (Mpris2Player *object);
gchar *mpris2_player_dup_playback_status (Mpris2Player *object);
void mpris2_player_set_playback_status (Mpris2Player *object, const gchar *value);

const gchar *mpris2_player_get_loop_status (Mpris2Player *object);
gchar *mpris2_player_dup_loop_status (Mpris2Player *object);
void mpris2_player_set_loop_status (Mpris2Player *object, const gchar *value);

gdouble mpris2_player_get_rate (Mpris2Player *object);
void mpris2_player_set_rate (Mpris2Player *object, gdouble value);

gboolean mpris2_player_get_shuffle (Mpris2Player *object);
void mpris2_player_set_shuffle (Mpris2Player *object, gboolean value);

GVariant *mpris2_player_get_metadata (Mpris2Player *object);
GVariant *mpris2_player_dup_metadata (Mpris2Player *object);
void mpris2_player_set_metadata (Mpris2Player *object, GVariant *value);

gdouble mpris2_player_get_volume (Mpris2Player *object);
void mpris2_player_set_volume (Mpris2Player *object, gdouble value);

gint64 mpris2_player_get_position (Mpris2Player *object);
void mpris2_player_set_position (Mpris2Player *object, gint64 value);

gdouble mpris2_player_get_minimum_rate (Mpris2Player *object);
void mpris2_player_set_minimum_rate (Mpris2Player *object, gdouble value);

gdouble mpris2_player_get_maximum_rate (Mpris2Player *object);
void mpris2_player_set_maximum_rate (Mpris2Player *object, gdouble value);

gboolean mpris2_player_get_can_go_next (Mpris2Player *object);
void mpris2_player_set_can_go_next (Mpris2Player *object, gboolean value);

gboolean mpris2_player_get_can_go_previous (Mpris2Player *object);
void mpris2_player_set_can_go_previous (Mpris2Player *object, gboolean value);

gboolean mpris2_player_get_can_play (Mpris2Player *object);
void mpris2_player_set_can_play (Mpris2Player *object, gboolean value);

gboolean mpris2_player_get_can_pause (Mpris2Player *object);
void mpris2_player_set_can_pause (Mpris2Player *object, gboolean value);

gboolean mpris2_player_get_can_seek (Mpris2Player *object);
void mpris2_player_set_can_seek (Mpris2Player *object, gboolean value);

gboolean mpris2_player_get_can_control (Mpris2Player *object);
void mpris2_player_set_can_control (Mpris2Player *object, gboolean value);


/* ---- */

#define MPRIS2_TYPE_PLAYER_PROXY (mpris2_player_proxy_get_type ())
#define MPRIS2_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS2_TYPE_PLAYER_PROXY, Mpris2PlayerProxy))
#define MPRIS2_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS2_TYPE_PLAYER_PROXY, Mpris2PlayerProxyClass))
#define MPRIS2_PLAYER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS2_TYPE_PLAYER_PROXY, Mpris2PlayerProxyClass))
#define MPRIS2_IS_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS2_TYPE_PLAYER_PROXY))
#define MPRIS2_IS_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS2_TYPE_PLAYER_PROXY))

typedef struct _Mpris2PlayerProxy Mpris2PlayerProxy;
typedef struct _Mpris2PlayerProxyClass Mpris2PlayerProxyClass;
typedef struct _Mpris2PlayerProxyPrivate Mpris2PlayerProxyPrivate;

struct _Mpris2PlayerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  Mpris2PlayerProxyPrivate *priv;
};

struct _Mpris2PlayerProxyClass
{
  GDBusProxyClass parent_class;
};

GType mpris2_player_proxy_get_type (void) G_GNUC_CONST;

void mpris2_player_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Mpris2Player *mpris2_player_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
Mpris2Player *mpris2_player_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void mpris2_player_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Mpris2Player *mpris2_player_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
Mpris2Player *mpris2_player_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MPRIS2_TYPE_PLAYER_SKELETON (mpris2_player_skeleton_get_type ())
#define MPRIS2_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MPRIS2_TYPE_PLAYER_SKELETON, Mpris2PlayerSkeleton))
#define MPRIS2_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MPRIS2_TYPE_PLAYER_SKELETON, Mpris2PlayerSkeletonClass))
#define MPRIS2_PLAYER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MPRIS2_TYPE_PLAYER_SKELETON, Mpris2PlayerSkeletonClass))
#define MPRIS2_IS_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MPRIS2_TYPE_PLAYER_SKELETON))
#define MPRIS2_IS_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MPRIS2_TYPE_PLAYER_SKELETON))

typedef struct _Mpris2PlayerSkeleton Mpris2PlayerSkeleton;
typedef struct _Mpris2PlayerSkeletonClass Mpris2PlayerSkeletonClass;
typedef struct _Mpris2PlayerSkeletonPrivate Mpris2PlayerSkeletonPrivate;

struct _Mpris2PlayerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  Mpris2PlayerSkeletonPrivate *priv;
};

struct _Mpris2PlayerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType mpris2_player_skeleton_get_type (void) G_GNUC_CONST;

Mpris2Player *mpris2_player_skeleton_new (void);


G_END_DECLS

#endif /* __MPRIS2_PLAYER_GENERATED_H__ */
