/*
 * Generated by gdbus-codegen 2.41.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "mpris2-tracklist-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.mpris.MediaPlayer2.TrackList
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:Mpris2TrackList
 * @title: Mpris2TrackList
 * @short_description: Generated C code for the org.mpris.MediaPlayer2.TrackList D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.mpris.MediaPlayer2.TrackList ---- */

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_get_tracks_metadata_IN_ARG_TrackIds =
{
  {
    -1,
    (gchar *) "TrackIds",
    (gchar *) "ao",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_method_info_get_tracks_metadata_IN_ARG_pointers[] =
{
  &_mpris2_track_list_method_info_get_tracks_metadata_IN_ARG_TrackIds,
  NULL
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_get_tracks_metadata_OUT_ARG_Metadata =
{
  {
    -1,
    (gchar *) "Metadata",
    (gchar *) "aa{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_method_info_get_tracks_metadata_OUT_ARG_pointers[] =
{
  &_mpris2_track_list_method_info_get_tracks_metadata_OUT_ARG_Metadata,
  NULL
};

static const _ExtendedGDBusMethodInfo _mpris2_track_list_method_info_get_tracks_metadata =
{
  {
    -1,
    (gchar *) "GetTracksMetadata",
    (GDBusArgInfo **) &_mpris2_track_list_method_info_get_tracks_metadata_IN_ARG_pointers,
    (GDBusArgInfo **) &_mpris2_track_list_method_info_get_tracks_metadata_OUT_ARG_pointers,
    NULL
  },
  "handle-get-tracks-metadata",
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_add_track_IN_ARG_Uri =
{
  {
    -1,
    (gchar *) "Uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_add_track_IN_ARG_AfterTrack =
{
  {
    -1,
    (gchar *) "AfterTrack",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_add_track_IN_ARG_SetAsCurrent =
{
  {
    -1,
    (gchar *) "SetAsCurrent",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_method_info_add_track_IN_ARG_pointers[] =
{
  &_mpris2_track_list_method_info_add_track_IN_ARG_Uri,
  &_mpris2_track_list_method_info_add_track_IN_ARG_AfterTrack,
  &_mpris2_track_list_method_info_add_track_IN_ARG_SetAsCurrent,
  NULL
};

static const _ExtendedGDBusMethodInfo _mpris2_track_list_method_info_add_track =
{
  {
    -1,
    (gchar *) "AddTrack",
    (GDBusArgInfo **) &_mpris2_track_list_method_info_add_track_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-add-track",
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_remove_track_IN_ARG_TrackId =
{
  {
    -1,
    (gchar *) "TrackId",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_method_info_remove_track_IN_ARG_pointers[] =
{
  &_mpris2_track_list_method_info_remove_track_IN_ARG_TrackId,
  NULL
};

static const _ExtendedGDBusMethodInfo _mpris2_track_list_method_info_remove_track =
{
  {
    -1,
    (gchar *) "RemoveTrack",
    (GDBusArgInfo **) &_mpris2_track_list_method_info_remove_track_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-remove-track",
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_method_info_go_to_IN_ARG_TrackId =
{
  {
    -1,
    (gchar *) "TrackId",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_method_info_go_to_IN_ARG_pointers[] =
{
  &_mpris2_track_list_method_info_go_to_IN_ARG_TrackId,
  NULL
};

static const _ExtendedGDBusMethodInfo _mpris2_track_list_method_info_go_to =
{
  {
    -1,
    (gchar *) "GoTo",
    (GDBusArgInfo **) &_mpris2_track_list_method_info_go_to_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-go-to",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _mpris2_track_list_method_info_pointers[] =
{
  &_mpris2_track_list_method_info_get_tracks_metadata,
  &_mpris2_track_list_method_info_add_track,
  &_mpris2_track_list_method_info_remove_track,
  &_mpris2_track_list_method_info_go_to,
  NULL
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_list_replaced_ARG_Tracks =
{
  {
    -1,
    (gchar *) "Tracks",
    (gchar *) "ao",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_list_replaced_ARG_CurrentTrack =
{
  {
    -1,
    (gchar *) "CurrentTrack",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_signal_info_track_list_replaced_ARG_pointers[] =
{
  &_mpris2_track_list_signal_info_track_list_replaced_ARG_Tracks,
  &_mpris2_track_list_signal_info_track_list_replaced_ARG_CurrentTrack,
  NULL
};

static const _ExtendedGDBusSignalInfo _mpris2_track_list_signal_info_track_list_replaced =
{
  {
    -1,
    (gchar *) "TrackListReplaced",
    (GDBusArgInfo **) &_mpris2_track_list_signal_info_track_list_replaced_ARG_pointers,
    NULL
  },
  "track-list-replaced"
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_added_ARG_Metadata =
{
  {
    -1,
    (gchar *) "Metadata",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_added_ARG_AfterTrack =
{
  {
    -1,
    (gchar *) "AfterTrack",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_signal_info_track_added_ARG_pointers[] =
{
  &_mpris2_track_list_signal_info_track_added_ARG_Metadata,
  &_mpris2_track_list_signal_info_track_added_ARG_AfterTrack,
  NULL
};

static const _ExtendedGDBusSignalInfo _mpris2_track_list_signal_info_track_added =
{
  {
    -1,
    (gchar *) "TrackAdded",
    (GDBusArgInfo **) &_mpris2_track_list_signal_info_track_added_ARG_pointers,
    NULL
  },
  "track-added"
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_removed_ARG_TrackId =
{
  {
    -1,
    (gchar *) "TrackId",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_signal_info_track_removed_ARG_pointers[] =
{
  &_mpris2_track_list_signal_info_track_removed_ARG_TrackId,
  NULL
};

static const _ExtendedGDBusSignalInfo _mpris2_track_list_signal_info_track_removed =
{
  {
    -1,
    (gchar *) "TrackRemoved",
    (GDBusArgInfo **) &_mpris2_track_list_signal_info_track_removed_ARG_pointers,
    NULL
  },
  "track-removed"
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_metadata_changed_ARG_TrackId =
{
  {
    -1,
    (gchar *) "TrackId",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _mpris2_track_list_signal_info_track_metadata_changed_ARG_Metadata =
{
  {
    -1,
    (gchar *) "Metadata",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _mpris2_track_list_signal_info_track_metadata_changed_ARG_pointers[] =
{
  &_mpris2_track_list_signal_info_track_metadata_changed_ARG_TrackId,
  &_mpris2_track_list_signal_info_track_metadata_changed_ARG_Metadata,
  NULL
};

static const _ExtendedGDBusSignalInfo _mpris2_track_list_signal_info_track_metadata_changed =
{
  {
    -1,
    (gchar *) "TrackMetadataChanged",
    (GDBusArgInfo **) &_mpris2_track_list_signal_info_track_metadata_changed_ARG_pointers,
    NULL
  },
  "track-metadata-changed"
};

static const _ExtendedGDBusSignalInfo * const _mpris2_track_list_signal_info_pointers[] =
{
  &_mpris2_track_list_signal_info_track_list_replaced,
  &_mpris2_track_list_signal_info_track_added,
  &_mpris2_track_list_signal_info_track_removed,
  &_mpris2_track_list_signal_info_track_metadata_changed,
  NULL
};

static const GDBusAnnotationInfo _mpris2_track_list_property_tracks_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "invalidates",
  NULL
};

static const GDBusAnnotationInfo * const _mpris2_track_list_property_tracks_annotation_info_pointers[] =
{
  &_mpris2_track_list_property_tracks_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _mpris2_track_list_property_info_tracks =
{
  {
    -1,
    (gchar *) "Tracks",
    (gchar *) "ao",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_mpris2_track_list_property_tracks_annotation_info_pointers
  },
  "tracks",
  FALSE,
  TRUE
};

static const GDBusAnnotationInfo _mpris2_track_list_property_can_edit_tracks_annotation_info_0 =
{
  -1,
  (gchar *) "org.freedesktop.DBus.Property.EmitsChangedSignal",
  (gchar *) "true",
  NULL
};

static const GDBusAnnotationInfo * const _mpris2_track_list_property_can_edit_tracks_annotation_info_pointers[] =
{
  &_mpris2_track_list_property_can_edit_tracks_annotation_info_0,
  NULL
};

static const _ExtendedGDBusPropertyInfo _mpris2_track_list_property_info_can_edit_tracks =
{
  {
    -1,
    (gchar *) "CanEditTracks",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    (GDBusAnnotationInfo **) &_mpris2_track_list_property_can_edit_tracks_annotation_info_pointers
  },
  "can-edit-tracks",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo * const _mpris2_track_list_property_info_pointers[] =
{
  &_mpris2_track_list_property_info_tracks,
  &_mpris2_track_list_property_info_can_edit_tracks,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _mpris2_track_list_interface_info =
{
  {
    -1,
    (gchar *) "org.mpris.MediaPlayer2.TrackList",
    (GDBusMethodInfo **) &_mpris2_track_list_method_info_pointers,
    (GDBusSignalInfo **) &_mpris2_track_list_signal_info_pointers,
    (GDBusPropertyInfo **) &_mpris2_track_list_property_info_pointers,
    NULL
  },
  "track-list",
};


/**
 * mpris2_track_list_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
mpris2_track_list_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct;
}

/**
 * mpris2_track_list_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #Mpris2TrackList interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
mpris2_track_list_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "tracks");
  g_object_class_override_property (klass, property_id_begin++, "can-edit-tracks");
  return property_id_begin - 1;
}



/**
 * Mpris2TrackList:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link>.
 */

/**
 * Mpris2TrackListIface:
 * @parent_iface: The parent interface.
 * @handle_add_track: Handler for the #Mpris2TrackList::handle-add-track signal.
 * @handle_get_tracks_metadata: Handler for the #Mpris2TrackList::handle-get-tracks-metadata signal.
 * @handle_go_to: Handler for the #Mpris2TrackList::handle-go-to signal.
 * @handle_remove_track: Handler for the #Mpris2TrackList::handle-remove-track signal.
 * @get_can_edit_tracks: Getter for the #Mpris2TrackList:can-edit-tracks property.
 * @get_tracks: Getter for the #Mpris2TrackList:tracks property.
 * @track_added: Handler for the #Mpris2TrackList::track-added signal.
 * @track_list_replaced: Handler for the #Mpris2TrackList::track-list-replaced signal.
 * @track_metadata_changed: Handler for the #Mpris2TrackList::track-metadata-changed signal.
 * @track_removed: Handler for the #Mpris2TrackList::track-removed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link>.
 */

typedef Mpris2TrackListIface Mpris2TrackListInterface;
G_DEFINE_INTERFACE (Mpris2TrackList, mpris2_track_list, G_TYPE_OBJECT);

static void
mpris2_track_list_default_init (Mpris2TrackListIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * Mpris2TrackList::handle-get-tracks-metadata:
   * @object: A #Mpris2TrackList.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_TrackIds: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GetTracksMetadata">GetTracksMetadata()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris2_track_list_complete_get_tracks_metadata() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-tracks-metadata",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, handle_get_tracks_metadata),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV);

  /**
   * Mpris2TrackList::handle-add-track:
   * @object: A #Mpris2TrackList.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_Uri: Argument passed by remote caller.
   * @arg_AfterTrack: Argument passed by remote caller.
   * @arg_SetAsCurrent: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.AddTrack">AddTrack()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris2_track_list_complete_add_track() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add-track",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, handle_add_track),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_BOOLEAN);

  /**
   * Mpris2TrackList::handle-remove-track:
   * @object: A #Mpris2TrackList.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_TrackId: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.RemoveTrack">RemoveTrack()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris2_track_list_complete_remove_track() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-remove-track",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, handle_remove_track),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * Mpris2TrackList::handle-go-to:
   * @object: A #Mpris2TrackList.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_TrackId: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GoTo">GoTo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call mpris2_track_list_complete_go_to() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-go-to",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, handle_go_to),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * Mpris2TrackList::track-list-replaced:
   * @object: A #Mpris2TrackList.
   * @arg_Tracks: Argument.
   * @arg_CurrentTrack: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackListReplaced">"TrackListReplaced"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("track-list-replaced",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, track_list_replaced),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRV, G_TYPE_STRING);

  /**
   * Mpris2TrackList::track-added:
   * @object: A #Mpris2TrackList.
   * @arg_Metadata: Argument.
   * @arg_AfterTrack: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackAdded">"TrackAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("track-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, track_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_VARIANT, G_TYPE_STRING);

  /**
   * Mpris2TrackList::track-removed:
   * @object: A #Mpris2TrackList.
   * @arg_TrackId: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackRemoved">"TrackRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("track-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, track_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * Mpris2TrackList::track-metadata-changed:
   * @object: A #Mpris2TrackList.
   * @arg_TrackId: Argument.
   * @arg_Metadata: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackMetadataChanged">"TrackMetadataChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("track-metadata-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (Mpris2TrackListIface, track_metadata_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_VARIANT);

  /* GObject properties for D-Bus properties: */
  /**
   * Mpris2TrackList:tracks:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.Tracks">"Tracks"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boxed ("tracks", "Tracks", "Tracks", G_TYPE_STRV, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * Mpris2TrackList:can-edit-tracks:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.CanEditTracks">"CanEditTracks"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("can-edit-tracks", "CanEditTracks", "CanEditTracks", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * mpris2_track_list_get_tracks: (skip)
 * @object: A #Mpris2TrackList.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.Tracks">"Tracks"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use mpris2_track_list_dup_tracks() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *const *
mpris2_track_list_get_tracks (Mpris2TrackList *object)
{
  return MPRIS2_TRACK_LIST_GET_IFACE (object)->get_tracks (object);
}

/**
 * mpris2_track_list_dup_tracks: (skip)
 * @object: A #Mpris2TrackList.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.Tracks">"Tracks"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_strfreev().
 */
gchar **
mpris2_track_list_dup_tracks (Mpris2TrackList *object)
{
  gchar **value;
  g_object_get (G_OBJECT (object), "tracks", &value, NULL);
  return value;
}

/**
 * mpris2_track_list_set_tracks: (skip)
 * @object: A #Mpris2TrackList.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.Tracks">"Tracks"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris2_track_list_set_tracks (Mpris2TrackList *object, const gchar *const *value)
{
  g_object_set (G_OBJECT (object), "tracks", value, NULL);
}

/**
 * mpris2_track_list_get_can_edit_tracks: (skip)
 * @object: A #Mpris2TrackList.
 *
 * Gets the value of the <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.CanEditTracks">"CanEditTracks"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
mpris2_track_list_get_can_edit_tracks (Mpris2TrackList *object)
{
  return MPRIS2_TRACK_LIST_GET_IFACE (object)->get_can_edit_tracks (object);
}

/**
 * mpris2_track_list_set_can_edit_tracks: (skip)
 * @object: A #Mpris2TrackList.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-mpris-MediaPlayer2-TrackList.CanEditTracks">"CanEditTracks"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
mpris2_track_list_set_can_edit_tracks (Mpris2TrackList *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "can-edit-tracks", value, NULL);
}

/**
 * mpris2_track_list_emit_track_list_replaced:
 * @object: A #Mpris2TrackList.
 * @arg_Tracks: Argument to pass with the signal.
 * @arg_CurrentTrack: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackListReplaced">"TrackListReplaced"</link> D-Bus signal.
 */
void
mpris2_track_list_emit_track_list_replaced (
    Mpris2TrackList *object,
    const gchar *const *arg_Tracks,
    const gchar *arg_CurrentTrack)
{
  g_signal_emit_by_name (object, "track-list-replaced", arg_Tracks, arg_CurrentTrack);
}

/**
 * mpris2_track_list_emit_track_added:
 * @object: A #Mpris2TrackList.
 * @arg_Metadata: Argument to pass with the signal.
 * @arg_AfterTrack: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackAdded">"TrackAdded"</link> D-Bus signal.
 */
void
mpris2_track_list_emit_track_added (
    Mpris2TrackList *object,
    GVariant *arg_Metadata,
    const gchar *arg_AfterTrack)
{
  g_signal_emit_by_name (object, "track-added", arg_Metadata, arg_AfterTrack);
}

/**
 * mpris2_track_list_emit_track_removed:
 * @object: A #Mpris2TrackList.
 * @arg_TrackId: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackRemoved">"TrackRemoved"</link> D-Bus signal.
 */
void
mpris2_track_list_emit_track_removed (
    Mpris2TrackList *object,
    const gchar *arg_TrackId)
{
  g_signal_emit_by_name (object, "track-removed", arg_TrackId);
}

/**
 * mpris2_track_list_emit_track_metadata_changed:
 * @object: A #Mpris2TrackList.
 * @arg_TrackId: Argument to pass with the signal.
 * @arg_Metadata: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-mpris-MediaPlayer2-TrackList.TrackMetadataChanged">"TrackMetadataChanged"</link> D-Bus signal.
 */
void
mpris2_track_list_emit_track_metadata_changed (
    Mpris2TrackList *object,
    const gchar *arg_TrackId,
    GVariant *arg_Metadata)
{
  g_signal_emit_by_name (object, "track-metadata-changed", arg_TrackId, arg_Metadata);
}

/**
 * mpris2_track_list_call_get_tracks_metadata:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackIds: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GetTracksMetadata">GetTracksMetadata()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_call_get_tracks_metadata_finish() to get the result of the operation.
 *
 * See mpris2_track_list_call_get_tracks_metadata_sync() for the synchronous, blocking version of this method.
 */
void
mpris2_track_list_call_get_tracks_metadata (
    Mpris2TrackList *proxy,
    const gchar *const *arg_TrackIds,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetTracksMetadata",
    g_variant_new ("(^ao)",
                   arg_TrackIds),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris2_track_list_call_get_tracks_metadata_finish:
 * @proxy: A #Mpris2TrackListProxy.
 * @out_Metadata: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_call_get_tracks_metadata().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris2_track_list_call_get_tracks_metadata().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_get_tracks_metadata_finish (
    Mpris2TrackList *proxy,
    GVariant **out_Metadata,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_Metadata);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_get_tracks_metadata_sync:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackIds: Argument to pass with the method invocation.
 * @out_Metadata: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GetTracksMetadata">GetTracksMetadata()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_call_get_tracks_metadata() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_get_tracks_metadata_sync (
    Mpris2TrackList *proxy,
    const gchar *const *arg_TrackIds,
    GVariant **out_Metadata,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetTracksMetadata",
    g_variant_new ("(^ao)",
                   arg_TrackIds),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_Metadata);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_add_track:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_Uri: Argument to pass with the method invocation.
 * @arg_AfterTrack: Argument to pass with the method invocation.
 * @arg_SetAsCurrent: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.AddTrack">AddTrack()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_call_add_track_finish() to get the result of the operation.
 *
 * See mpris2_track_list_call_add_track_sync() for the synchronous, blocking version of this method.
 */
void
mpris2_track_list_call_add_track (
    Mpris2TrackList *proxy,
    const gchar *arg_Uri,
    const gchar *arg_AfterTrack,
    gboolean arg_SetAsCurrent,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "AddTrack",
    g_variant_new ("(sob)",
                   arg_Uri,
                   arg_AfterTrack,
                   arg_SetAsCurrent),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris2_track_list_call_add_track_finish:
 * @proxy: A #Mpris2TrackListProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_call_add_track().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris2_track_list_call_add_track().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_add_track_finish (
    Mpris2TrackList *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_add_track_sync:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_Uri: Argument to pass with the method invocation.
 * @arg_AfterTrack: Argument to pass with the method invocation.
 * @arg_SetAsCurrent: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.AddTrack">AddTrack()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_call_add_track() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_add_track_sync (
    Mpris2TrackList *proxy,
    const gchar *arg_Uri,
    const gchar *arg_AfterTrack,
    gboolean arg_SetAsCurrent,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "AddTrack",
    g_variant_new ("(sob)",
                   arg_Uri,
                   arg_AfterTrack,
                   arg_SetAsCurrent),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_remove_track:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackId: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.RemoveTrack">RemoveTrack()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_call_remove_track_finish() to get the result of the operation.
 *
 * See mpris2_track_list_call_remove_track_sync() for the synchronous, blocking version of this method.
 */
void
mpris2_track_list_call_remove_track (
    Mpris2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "RemoveTrack",
    g_variant_new ("(o)",
                   arg_TrackId),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris2_track_list_call_remove_track_finish:
 * @proxy: A #Mpris2TrackListProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_call_remove_track().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris2_track_list_call_remove_track().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_remove_track_finish (
    Mpris2TrackList *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_remove_track_sync:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackId: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.RemoveTrack">RemoveTrack()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_call_remove_track() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_remove_track_sync (
    Mpris2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "RemoveTrack",
    g_variant_new ("(o)",
                   arg_TrackId),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_go_to:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackId: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GoTo">GoTo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_call_go_to_finish() to get the result of the operation.
 *
 * See mpris2_track_list_call_go_to_sync() for the synchronous, blocking version of this method.
 */
void
mpris2_track_list_call_go_to (
    Mpris2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GoTo",
    g_variant_new ("(o)",
                   arg_TrackId),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * mpris2_track_list_call_go_to_finish:
 * @proxy: A #Mpris2TrackListProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_call_go_to().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with mpris2_track_list_call_go_to().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_go_to_finish (
    Mpris2TrackList *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_call_go_to_sync:
 * @proxy: A #Mpris2TrackListProxy.
 * @arg_TrackId: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GoTo">GoTo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_call_go_to() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
mpris2_track_list_call_go_to_sync (
    Mpris2TrackList *proxy,
    const gchar *arg_TrackId,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GoTo",
    g_variant_new ("(o)",
                   arg_TrackId),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * mpris2_track_list_complete_get_tracks_metadata:
 * @object: A #Mpris2TrackList.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @Metadata: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GetTracksMetadata">GetTracksMetadata()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris2_track_list_complete_get_tracks_metadata (
    Mpris2TrackList *object,
    GDBusMethodInvocation *invocation,
    GVariant *Metadata)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aa{sv})",
                   Metadata));
}

/**
 * mpris2_track_list_complete_add_track:
 * @object: A #Mpris2TrackList.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.AddTrack">AddTrack()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris2_track_list_complete_add_track (
    Mpris2TrackList *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mpris2_track_list_complete_remove_track:
 * @object: A #Mpris2TrackList.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.RemoveTrack">RemoveTrack()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris2_track_list_complete_remove_track (
    Mpris2TrackList *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * mpris2_track_list_complete_go_to:
 * @object: A #Mpris2TrackList.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mpris-MediaPlayer2-TrackList.GoTo">GoTo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
mpris2_track_list_complete_go_to (
    Mpris2TrackList *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * Mpris2TrackListProxy:
 *
 * The #Mpris2TrackListProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Mpris2TrackListProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Mpris2TrackListProxy.
 */

struct _Mpris2TrackListProxyPrivate
{
  GData *qdata;
};

static void mpris2_track_list_proxy_iface_init (Mpris2TrackListIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Mpris2TrackListProxy, mpris2_track_list_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (Mpris2TrackListProxy)
                         G_IMPLEMENT_INTERFACE (MPRIS2_TYPE_TRACK_LIST, mpris2_track_list_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Mpris2TrackListProxy, mpris2_track_list_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (MPRIS2_TYPE_TRACK_LIST, mpris2_track_list_proxy_iface_init));

#endif
static void
mpris2_track_list_proxy_finalize (GObject *object)
{
  Mpris2TrackListProxy *proxy = MPRIS2_TRACK_LIST_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (mpris2_track_list_proxy_parent_class)->finalize (object);
}

static void
mpris2_track_list_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  info = _mpris2_track_list_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
mpris2_track_list_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.mpris.MediaPlayer2.TrackList: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
mpris2_track_list_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  info = _mpris2_track_list_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.mpris.MediaPlayer2.TrackList", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) mpris2_track_list_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
mpris2_track_list_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], MPRIS2_TYPE_TRACK_LIST);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MPRIS2_TYPE_TRACK_LIST);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
mpris2_track_list_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  Mpris2TrackListProxy *proxy = MPRIS2_TRACK_LIST_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *const *
mpris2_track_list_proxy_get_tracks (Mpris2TrackList *object)
{
  Mpris2TrackListProxy *proxy = MPRIS2_TRACK_LIST_PROXY (object);
  GVariant *variant;
  const gchar *const *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Tracks");
  if (variant != NULL)
    {
      value = g_variant_get_objv (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
mpris2_track_list_proxy_get_can_edit_tracks (Mpris2TrackList *object)
{
  Mpris2TrackListProxy *proxy = MPRIS2_TRACK_LIST_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "CanEditTracks");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
mpris2_track_list_proxy_init (Mpris2TrackListProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = mpris2_track_list_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, MPRIS2_TYPE_TRACK_LIST_PROXY, Mpris2TrackListProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), mpris2_track_list_interface_info ());
}

static void
mpris2_track_list_proxy_class_init (Mpris2TrackListProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = mpris2_track_list_proxy_finalize;
  gobject_class->get_property = mpris2_track_list_proxy_get_property;
  gobject_class->set_property = mpris2_track_list_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = mpris2_track_list_proxy_g_signal;
  proxy_class->g_properties_changed = mpris2_track_list_proxy_g_properties_changed;

  mpris2_track_list_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Mpris2TrackListProxyPrivate));
#endif
}

static void
mpris2_track_list_proxy_iface_init (Mpris2TrackListIface *iface)
{
  iface->get_tracks = mpris2_track_list_proxy_get_tracks;
  iface->get_can_edit_tracks = mpris2_track_list_proxy_get_can_edit_tracks;
}

/**
 * mpris2_track_list_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_proxy_new_finish() to get the result of the operation.
 *
 * See mpris2_track_list_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
mpris2_track_list_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MPRIS2_TYPE_TRACK_LIST_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2.TrackList", NULL);
}

/**
 * mpris2_track_list_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mpris2_track_list_proxy_new().
 *
 * Returns: (transfer full) (type Mpris2TrackListProxy): The constructed proxy object or %NULL if @error is set.
 */
Mpris2TrackList *
mpris2_track_list_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MPRIS2_TRACK_LIST (ret);
  else
    return NULL;
}

/**
 * mpris2_track_list_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Mpris2TrackListProxy): The constructed proxy object or %NULL if @error is set.
 */
Mpris2TrackList *
mpris2_track_list_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MPRIS2_TYPE_TRACK_LIST_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2.TrackList", NULL);
  if (ret != NULL)
    return MPRIS2_TRACK_LIST (ret);
  else
    return NULL;
}


/**
 * mpris2_track_list_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like mpris2_track_list_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call mpris2_track_list_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See mpris2_track_list_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
mpris2_track_list_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MPRIS2_TYPE_TRACK_LIST_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2.TrackList", NULL);
}

/**
 * mpris2_track_list_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to mpris2_track_list_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with mpris2_track_list_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type Mpris2TrackListProxy): The constructed proxy object or %NULL if @error is set.
 */
Mpris2TrackList *
mpris2_track_list_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MPRIS2_TRACK_LIST (ret);
  else
    return NULL;
}

/**
 * mpris2_track_list_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like mpris2_track_list_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See mpris2_track_list_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type Mpris2TrackListProxy): The constructed proxy object or %NULL if @error is set.
 */
Mpris2TrackList *
mpris2_track_list_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MPRIS2_TYPE_TRACK_LIST_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.mpris.MediaPlayer2.TrackList", NULL);
  if (ret != NULL)
    return MPRIS2_TRACK_LIST (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * Mpris2TrackListSkeleton:
 *
 * The #Mpris2TrackListSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * Mpris2TrackListSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #Mpris2TrackListSkeleton.
 */

struct _Mpris2TrackListSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_mpris2_track_list_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], MPRIS2_TYPE_TRACK_LIST);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MPRIS2_TYPE_TRACK_LIST);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_mpris2_track_list_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_mpris2_track_list_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_mpris2_track_list_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _mpris2_track_list_skeleton_vtable =
{
  _mpris2_track_list_skeleton_handle_method_call,
  _mpris2_track_list_skeleton_handle_get_property,
  _mpris2_track_list_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
mpris2_track_list_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return mpris2_track_list_interface_info ();
}

static GDBusInterfaceVTable *
mpris2_track_list_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_mpris2_track_list_skeleton_vtable;
}

static GVariant *
mpris2_track_list_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_mpris2_track_list_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _mpris2_track_list_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _mpris2_track_list_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _mpris2_track_list_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2.TrackList", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _mpris2_track_list_emit_changed (gpointer user_data);

static void
mpris2_track_list_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _mpris2_track_list_emit_changed (skeleton);
}

static void
_mpris2_track_list_on_signal_track_list_replaced (
    Mpris2TrackList *object,
    const gchar *const *arg_Tracks,
    const gchar *arg_CurrentTrack)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(^aoo)",
                   arg_Tracks,
                   arg_CurrentTrack));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2.TrackList", "TrackListReplaced",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_mpris2_track_list_on_signal_track_added (
    Mpris2TrackList *object,
    GVariant *arg_Metadata,
    const gchar *arg_AfterTrack)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(@a{sv}o)",
                   arg_Metadata,
                   arg_AfterTrack));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2.TrackList", "TrackAdded",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_mpris2_track_list_on_signal_track_removed (
    Mpris2TrackList *object,
    const gchar *arg_TrackId)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_TrackId));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2.TrackList", "TrackRemoved",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_mpris2_track_list_on_signal_track_metadata_changed (
    Mpris2TrackList *object,
    const gchar *arg_TrackId,
    GVariant *arg_Metadata)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o@a{sv})",
                   arg_TrackId,
                   arg_Metadata));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.mpris.MediaPlayer2.TrackList", "TrackMetadataChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void mpris2_track_list_skeleton_iface_init (Mpris2TrackListIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (Mpris2TrackListSkeleton, mpris2_track_list_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (Mpris2TrackListSkeleton)
                         G_IMPLEMENT_INTERFACE (MPRIS2_TYPE_TRACK_LIST, mpris2_track_list_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (Mpris2TrackListSkeleton, mpris2_track_list_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (MPRIS2_TYPE_TRACK_LIST, mpris2_track_list_skeleton_iface_init));

#endif
static void
mpris2_track_list_skeleton_finalize (GObject *object)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  guint n;
  for (n = 0; n < 2; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (mpris2_track_list_skeleton_parent_class)->finalize (object);
}

static void
mpris2_track_list_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_mpris2_track_list_emit_changed (gpointer user_data)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.mpris.MediaPlayer2.TrackList",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_mpris2_track_list_schedule_emit_changed (Mpris2TrackListSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
mpris2_track_list_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _mpris2_track_list_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _mpris2_track_list_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
mpris2_track_list_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 2);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          _mpris2_track_list_property_info_pointers[prop_id - 1]->emits_changed_signal)
        _mpris2_track_list_schedule_emit_changed (skeleton, _mpris2_track_list_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
mpris2_track_list_skeleton_init (Mpris2TrackListSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = mpris2_track_list_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, MPRIS2_TYPE_TRACK_LIST_SKELETON, Mpris2TrackListSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 2);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRV);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
}

static const gchar *const *
mpris2_track_list_skeleton_get_tracks (Mpris2TrackList *object)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  const gchar *const *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boxed (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
mpris2_track_list_skeleton_get_can_edit_tracks (Mpris2TrackList *object)
{
  Mpris2TrackListSkeleton *skeleton = MPRIS2_TRACK_LIST_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
mpris2_track_list_skeleton_class_init (Mpris2TrackListSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = mpris2_track_list_skeleton_finalize;
  gobject_class->get_property = mpris2_track_list_skeleton_get_property;
  gobject_class->set_property = mpris2_track_list_skeleton_set_property;
  gobject_class->notify       = mpris2_track_list_skeleton_notify;


  mpris2_track_list_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = mpris2_track_list_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = mpris2_track_list_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = mpris2_track_list_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = mpris2_track_list_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (Mpris2TrackListSkeletonPrivate));
#endif
}

static void
mpris2_track_list_skeleton_iface_init (Mpris2TrackListIface *iface)
{
  iface->track_list_replaced = _mpris2_track_list_on_signal_track_list_replaced;
  iface->track_added = _mpris2_track_list_on_signal_track_added;
  iface->track_removed = _mpris2_track_list_on_signal_track_removed;
  iface->track_metadata_changed = _mpris2_track_list_on_signal_track_metadata_changed;
  iface->get_tracks = mpris2_track_list_skeleton_get_tracks;
  iface->get_can_edit_tracks = mpris2_track_list_skeleton_get_can_edit_tracks;
}

/**
 * mpris2_track_list_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-mpris-MediaPlayer2-TrackList.top_of_page">org.mpris.MediaPlayer2.TrackList</link>.
 *
 * Returns: (transfer full) (type Mpris2TrackListSkeleton): The skeleton object.
 */
Mpris2TrackList *
mpris2_track_list_skeleton_new (void)
{
  return MPRIS2_TRACK_LIST (g_object_new (MPRIS2_TYPE_TRACK_LIST_SKELETON, NULL));
}

